[tool.portray]
output_dir = "portraydocs"
modules = ["discord-oauth2"]

[tool.portray.mkdocs.theme]
name = "material"
palette = {primary = "black", accent = "blue"}

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
Usage = "docs/hi.md"

[tool.portray.mkdocs]
repo_url = "https://github.com/paulablaza/discord-oauth2"
repo_name = "discord-oauth2"
edit_uri = "none"
