name: Create Docs
on: [push]

jobs:
  Create-Docs:
    runs-on: ubuntu-latest

    steps:
      - run: ls
      - run: pip install portray
      - run: python -m portray as_html -o portraydocs --overwrite
