name: Create Docs
on: [push]

jobs:
  Create-Docs:
    runs-on: ubuntu-latest

    steps:
      - run: pip install portray
      - run: python -m portray as_html -o portraydocs -m /github/workspace/discord_outh2 --overwrite
